ARG APP_ROOT=/app

# production environment
FROM nginx:alpine
ARG APP_ROOT
ENV APP_DIR=$APP_ROOT
RUN rm -rf /etc/nginx/conf.d
COPY deploy/default.conf /etc/nginx/conf.d/
COPY deploy/nginx.conf /etc/nginx/
COPY deploy/start.sh ./
COPY deploy/ssl/ca_bundled.crt deploy/ssl/private.key /etc/ssl/
COPY --from=backpackerdeals_express ${APP_ROOT}/.next/static /usr/share/nginx/static
EXPOSE 80 443
ENTRYPOINT [ "./start.sh" ]