export const cards = [
  {
    img: require('./assets/picture1.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal' as any,
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture2.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: undefined,
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture3.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal' as any,
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture1.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: 'mostPopular',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture2.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture3.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: '',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture1.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture2.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: 'mostPopular',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture3.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture1.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: '',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture2.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture3.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: 'mostPopular',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture1.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture2.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: 'AUD$300',
    saleType: '',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
  {
    img: require('./assets/picture3.jpg?resize&sizes[]=272&sizes[]=312&sizes[]=356&sizes[]=496'),
    tourName: 'Kakadu 4WD Adventure',
    price: 900,
    location: 'Australia, Sydney',
    sale: '30% OFF',
    saleType: 'topDeal',
    value: 1200,
    duration: '2 days, 1 night',
    rating: 4.5,
    exposeTime: {
      days: '02',
      hours: '10',
      minutes: '51',
    },
    description: 'Explore one of the world`s oldest and most spectacular mountain ranges in the heart of Victoria on this full day adventure from Melbourne.',
    sizes: "(max-width: 767px) 272px, (max-width: 1024px) 312px, (max-width: 1280px) 356px, 496px"
  },
]

export const filters = [
  "Adelaide (10)",
  "Hervey Bay (1)",
  "Agnes Water (2)",
  "Hobart (22)",
  "Airlie Beach(1)",
  "Whitsundays (16)",
  "Kakadu (13)",
  "Alice Springs (21)",
  "Launceston (6)",
  "Ayers Rock (19)",
  "Melbourne (39)",
  "Brisbane (7)",
  "Noosa (2)",
  "Broome (1)",
  "Perth (13)",
  "Byron Bay (16)"
]