export const FILTERS_MENU_OPEN = 'FILTERS_MENU_OPEN'
export const FILTERS_MENU_CLOSE = 'FILTERS_MENU_CLOSE'

export const MOBILE_SEARCH_OPEN = 'MOBILE_SEARCH_OPEN'
export const MOBILE_SEARCH_CLOSE = 'MOBILE_SEARCH_CLOSE'
export const SEARCH_TYPE_CHANGE = 'SEARCH_TYPE_CHANGE'

export const CONTEXT_SEARCH_REQUEST = 'CONTEXT_SEARCH_REQUEST'
export const CONTEXT_SEARCH_SUCCESS = 'CONTEXT_SEARCH_SUCCESS'
export const CONTEXT_SEARCH_FAILURE = 'CONTEXT_SEARCH_FAILURE'