version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependeces
          command: |
            apk update && apk add openssl
      - run:
          name: Decrypt & add SSH Key
          command: |
            openssl aes-256-cbc -d -in deploy_rsa.enc -out /tmp/deploy_rsa -k $KEY
            chmod 600 /tmp/deploy_rsa
            ssh-add /tmp/deploy_rsa
      - run:
          name: Build application Docker image
          command: |
            docker build -t backpackerdeals .
      - deploy:
          name: Push application Docker image
          command: |
            docker save backpackerdeals | bzip2 | ssh -o "StrictHostKeyChecking no" rulevoi@cs.istu.ru "ssh -i ./bpd4.pem ubuntu@bpd4.backpackerdeals.com 'bunzip2 | docker load && ./start.sh'"