version: 2
jobs:
  build:
    branches:
      only:
        - master
    working_directory: /app
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependeces
          command: |
            apk update && apk add openssl
      - run:
          name: Decrypt & add SSH Key
          command: |
            openssl aes-256-cbc -d -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -k $KEY
            chmod 600 /tmp/deploy_rsa
            ssh-add /tmp/deploy_rsa
      - run:
          name: Decrypt Certificates
          command: |
            openssl aes-256-cbc -d -in deploy/ssl/ca_bundled.crt.enc -out deploy/ssl/ca_bundled.crt -k $KEY
            openssl aes-256-cbc -d -in deploy/ssl/private.key.enc -out deploy/ssl/private.key -k $KEY
      - run:
          name: Build Express Docker image
          command: |
            docker build -t backpackerdeals_express .
      - run:
          name: Build Nginx Docker image
          command: |
            docker build -f Dockerfile.nginx -t backpackerdeals_nginx .
      - deploy:
          name: Push application Docker image
          command: |
            docker save backpackerdeals_express | ssh -o "StrictHostKeyChecking no" rulevoi@cs.istu.ru "ssh -i ./bpd4.pem ubuntu@bpd4.backpackerdeals.com 'docker load'"
            docker save backpackerdeals_nginx | ssh -o "StrictHostKeyChecking no" rulevoi@cs.istu.ru "ssh -i ./bpd4.pem ubuntu@bpd4.backpackerdeals.com 'docker load && ./start.sh'"