export interface IConfigItem {
  id: number
  name: string
  unique_name: string
  travel_stats?: any
  cities?: any
}

export default {
  categories: [
    { name: 'Adventure', unique_name: 'adventure', id: 1 },
    { name: 'Attractions', unique_name: 'attractions', id: 2 },
    { name: 'Cruise & Sailing', unique_name: 'cruise-sailing', id: 4 },
    { name: 'Snow Tours', unique_name: 'snow-tours', id: 5 },
    { name: 'Dive & Snorkelling', unique_name: 'dive-and-surf', id: 6 },
    { name: 'Day Trips & Excursions', unique_name: 'day-trips-excursions', id: 8 },
    { name: 'Wine Tasting', unique_name: 'wine-tasting', id: 9 },
    { name: 'Accommodation', unique_name: 'accommodation', id: 10 },
    { name: 'Getting Around', unique_name: 'getting-around', id: 11 },
    { name: 'Skydiving', unique_name: 'skydiving', id: 12 },
    { name: 'Water Activities', unique_name: 'water-activities', id: 13 },
    { name: 'Adrenaline', unique_name: 'adrenaline', id: 14 },
    { name: 'Multi-Day Tours', unique_name: 'multi-day-tours', id: 16 },
    { name: 'Local Tours', unique_name: 'local-tours', id: 18 },
    { name: 'Cultural Tours', unique_name: 'cultural-tours', id: 19 },
    { name: 'Wildlife & Nature', unique_name: 'wildlife-nature-tours', id: 22 },
    { name: 'Bus Passes', unique_name: 'bus-passes', id: 26 },
    { name: 'Car & Campervan', unique_name: 'car-campervan-rental', id: 27 },
    { name: 'Whale & Dolphin Watching', unique_name: 'whale-dolphin-watching', id: 28 },
    { name: 'Zoos & Wildlife Sanctuaries', unique_name: 'zoos-wildlife-sanctuaries', id: 29 },
    { name: 'Jet Boating', unique_name: 'jet-boating', id: 30 },
    { name: 'Surfing & SUP', unique_name: 'surfing-sup', id: 31 },
    { name: 'Kayaking', unique_name: 'kayaking', id: 32 },
    { name: 'Canyoning', unique_name: 'canyoning', id: 33 },
    { name: 'Rafting', unique_name: 'rafting', id: 34 },
    { name: 'Bungee Jumping', unique_name: 'bungee-jumping', id: 35 },
    { name: 'Shark Diving', unique_name: 'shark-diving', id: 36 },
    { name: 'Food, Wine & Nightlife', unique_name: 'food-wine-nightlife', id: 37 },
    { name: 'Brewery Tours', unique_name: 'brewery-tours', id: 38 },
    { name: 'Pub Crawl & Party', unique_name: 'pub-crawl-party', id: 39 },
    { name: 'Food Tours', unique_name: 'food-tours', id: 40 },
    { name: 'Classes & Workshops', unique_name: 'workshops', id: 41 },
    { name: 'Air, Helicopter & Ballooning', unique_name: 'air-helicopter-hot-air-ballooning', id: 42 },
    { name: 'Camping', unique_name: 'camping', id: 43 },
    { name: 'National Parks', unique_name: 'national-parks', id: 44 },
    { name: 'Bus Passes No', unique_name: 'bus-passes-no', id: 20 },
    { name: 'Car & Campervan No', unique_name: 'car-campervan-rentals-no', id: 21 },
    { name: 'Whale & Dolphin Watching No', unique_name: 'whale-dolphin-watching-no', id: 23 },
    { name: 'Outback Tours', unique_name: 'outback-tours', id: 24 },
    { name: 'National Parks-NO', unique_name: 'national-parks-no', id: 25 },
    { name: 'Walking & Biking Tours', unique_name: 'walking-biking-tours', id: 45 },
    { name: 'Parasailing', unique_name: 'parasailing', id: 46 },
    { name: 'Mountain Biking', unique_name: 'mountain-biking', id: 47 },
    { name: '4WD', unique_name: '4wd', id: 48 },
    { name: 'Top End Tours', unique_name: 'top-end-tours', id: 49 },
    { name: 'Overland Tours', unique_name: 'overland-tours', id: 50 },
    { name: 'Festivals', unique_name: 'festivals', id: 51 },
    { name: 'Ziplining', unique_name: 'ziplining', id: 52 },
  ],
  countries: [
    {
      cities: [
        { name: 'Sydney', unique_name: 'sydney', id: 16, travel_stats: { '16': '23', '22': '1', '25': '1', '63': '1' } },
        { name: 'Melbourne', unique_name: 'melbourne', id: 17, travel_stats: { '17': '32', '20': '2', '171': '1', '180': '1' } },
        { name: 'Brisbane', unique_name: 'brisbane', id: 18, travel_stats: { '18': '10', '21': '3', '63': '1', '174': '2', '177': '1' } },
        { name: 'Perth', unique_name: 'perth', id: 19, travel_stats: { '19': '10', '20': '1', '328': '1' } },
        {
          name: 'Adelaide',
          unique_name: 'adelaide',
          id: 20,
          travel_stats: { '17': '2', '19': '1', '20': '3', '171': '1', '172': '2', '180': '1', '246': '2' },
        },
        { name: 'Gold Coast', unique_name: 'gold-coast', id: 21, travel_stats: { '18': '3', '21': '12', '63': '1', '174': '1' } },
        { name: 'Cairns', unique_name: 'cairns', id: 30, travel_stats: { '30': '24', '171': '1' } },
        { name: 'Launceston', unique_name: 'launceston', id: 33, travel_stats: { '254': '5' } },
        { name: 'Hervey Bay', unique_name: 'hervey-bay', id: 44 },
        { name: 'Byron Bay', unique_name: 'byron-bay', id: 63, travel_stats: { '16': '1', '18': '1', '21': '1', '63': '14' } },
        { name: 'Fraser Island', unique_name: 'fraser-island', id: 148, travel_stats: { '148': '5', '174': '3', '177': '2' } },
        { name: 'Port Lincoln', unique_name: 'port-lincoln', id: 149, travel_stats: { '149': '2' } },
        { name: 'Tasmania', unique_name: 'tasmania', id: 151, travel_stats: { '254': '1' } },
        {
          name: 'Alice Springs',
          unique_name: 'alice-springs',
          id: 171,
          travel_stats: { '20': '1', '171': '8', '172': '1', '180': '2', '246': '2' },
        },
        { name: 'Ayers Rock', unique_name: 'ayers-rock', id: 172, travel_stats: { '171': '3', '172': '9', '246': '9' } },
        { name: 'Noosa', unique_name: 'noosa', id: 174, travel_stats: { '18': '2', '21': '1', '148': '3', '174': '8', '177': '3' } },
        { name: 'Airlie Beach/Whitsundays', unique_name: 'airlie-beach-whitsundays', id: 176, travel_stats: { '176': '22' } },
        { name: 'Rainbow Beach', unique_name: 'rainbow-beach', id: 177, travel_stats: { '18': '1', '148': '2', '174': '3', '177': '4' } },
        { name: 'Port Stephens', unique_name: 'port-stephens', id: 178 },
        { name: 'Darwin', unique_name: 'darwin', id: 180, travel_stats: { '171': '2', '172': '1', '180': '17', '246': '1', '258': '2' } },
        { name: 'Agnes Water', unique_name: 'agnes-water', id: 235, travel_stats: { '235': '1' } },
        { name: 'Great Ocean Road', unique_name: 'great-ocean-road', id: 243 },
        { name: 'Kakadu', unique_name: 'kakadu', id: 244 },
        { name: 'Great Barrier Reef', unique_name: 'great-barrier-reef', id: 245 },
        { name: 'Uluru (Ayers Rock)', unique_name: 'uluru', id: 246, travel_stats: { '171': '4', '172': '9', '246': '9' } },
        { name: 'Hobart', unique_name: 'hobart', id: 254, travel_stats: { '33': '2', '254': '19' } },
        { name: 'Broome', unique_name: 'broome', id: 258, travel_stats: { '180': '2' } },
        { name: 'Port Douglas', unique_name: 'port-douglas', id: 274, travel_stats: { '274': '1' } },
        { name: 'Airlie Beach', unique_name: 'airlie-beach', id: 322 },
        { name: 'Exmouth', unique_name: 'exmouth', id: 328, travel_stats: { '328': '2' } },
        { name: 'Flametree', unique_name: 'flametree', id: 333 },
      ],
      name: 'Australia',
      iso_code: 'AU',
      unique_name: 'australia',
      id: 2,
    },
    {
      cities: [{ name: 'Siem Reap', unique_name: 'siem-reap', id: 192 }, { name: 'Phnom Penh', unique_name: 'phnom-penh', id: 204 }],
      name: 'Cambodia',
      iso_code: 'KH',
      unique_name: 'cambodia',
      id: 5,
    },
    {
      cities: [{ name: 'Bogota', unique_name: 'bogota', id: 210, travel_stats: { '210': '5' } }],
      name: 'Colombia',
      iso_code: 'CO',
      unique_name: 'colombia',
      id: 67,
    },
    {
      cities: [
        { name: 'San Jose', unique_name: 'san-jose', id: 125 },
        { name: 'Manuel Antonio', unique_name: 'manuel-antonio', id: 128 },
        { name: 'Quepos', unique_name: 'quepos', id: 343 },
        { name: 'Rinc\u00f3n de la Vieja', unique_name: 'rincon-de-la-vieja', id: 345 },
        { name: 'Palo Verde', unique_name: 'paloverde', id: 346 },
        { name: 'Liberia', unique_name: 'liberia', id: 347 },
        { name: 'Tilar\u00e1n', unique_name: 'tilaran', id: 348 },
        { name: 'Monteverde', unique_name: 'monteverde', id: 349, travel_stats: { '349': '1' } },
        { name: 'La Fortuna', unique_name: 'la-fortuna', id: 350 },
        { name: 'Puntarenas', unique_name: 'puntarenas', id: 354 },
        { name: 'Nuevo Arenal', unique_name: 'nuevo-arenal', id: 356 },
        { name: 'Jac\u00f3', unique_name: 'jaco', id: 363 },
      ],
      name: 'Costa Rica',
      iso_code: 'CR',
      unique_name: 'costa-rica',
      id: 17,
    },
    {
      cities: [
        { name: 'Sigatoka', unique_name: 'sigatoka', id: 106 },
        { name: 'Taveuni Island', unique_name: 'taveuni-island', id: 110 },
        { name: 'Nadi', unique_name: 'nadi', id: 226 },
      ],
      name: 'Fiji',
      iso_code: 'FJ',
      unique_name: 'fiji',
      id: 23,
    },
    {
      cities: [{ name: 'Munich', unique_name: 'munich', id: 335, travel_stats: { '335': '1' } }],
      name: 'Germany',
      iso_code: 'DE',
      unique_name: 'germany',
      id: 97,
    },
    {
      cities: [
        { name: 'Tokyo', unique_name: 'tokyo', id: 187 },
        { name: 'Osaka', unique_name: 'osaka', id: 188 },
        { name: 'Kyoto', unique_name: 'kyoto', id: 189 },
        { name: 'Nagano', unique_name: 'nagano', id: 273 },
      ],
      name: 'Japan',
      iso_code: 'JP',
      unique_name: 'japan',
      id: 122,
    },
    {
      cities: [
        { name: 'Auckland', unique_name: 'auckland', id: 1, travel_stats: { '1': '32', '2': '1', '179': '4' } },
        { name: 'Wellington', unique_name: 'wellington', id: 2, travel_stats: { '2': '1' } },
        { name: 'Rotorua', unique_name: 'rotorua', id: 10, travel_stats: { '6': '1', '10': '27', '318': '1' } },
        { name: 'Queenstown', unique_name: 'queenstown', id: 60, travel_stats: { '60': '54', '249': '2', '313': '2' } },
        { name: 'Taupo', unique_name: 'taupo', id: 61, travel_stats: { '61': '10' } },
        { name: 'Bay of Islands', unique_name: 'bay-of-islands', id: 91, travel_stats: { '91': '12', '129': '6' } },
        { name: 'Coromandel', unique_name: 'coromandel', id: 133 },
        { name: 'Waitomo', unique_name: 'waitomo', id: 135, travel_stats: { '135': '7' } },
        { name: 'Franz Josef', unique_name: 'franz-josef', id: 156, travel_stats: { '156': '7', '330': '1' } },
        { name: 'Christchurch', unique_name: 'christchurch', id: 179, travel_stats: { '1': '1', '179': '7' } },
        { name: 'Motueka', unique_name: 'motueka', id: 240, travel_stats: { '240': '1' } },
        { name: 'Franz Josef Glacier', unique_name: 'franz-josef-glacier', id: 248 },
        { name: 'Glenorchy', unique_name: 'glenorchy', id: 249, travel_stats: { '60': '2', '249': '3' } },
        { name: 'Lake Tekapo', unique_name: 'lake-tekapo', id: 291, travel_stats: { '291': '1' } },
        { name: 'Wanaka', unique_name: 'wanaka', id: 313, travel_stats: { '60': '2', '313': '10' } },
        { name: 'Te Anau', unique_name: 'te-anau', id: 314, travel_stats: { '314': '3' } },
        { name: 'Whakatane', unique_name: 'whakatane', id: 318, travel_stats: { '6': '1', '10': '1', '318': '1' } },
        { name: 'Milford Sound', unique_name: 'milford-sound', id: 320, travel_stats: { '320': '1' } },
        { name: 'Kaikoura', unique_name: 'kaikoura', id: 325, travel_stats: { '325': '1' } },
        { name: 'Fox Glacier', unique_name: 'fox-glacier', id: 330, travel_stats: { '156': '1', '330': '4' } },
        { name: 'Mount Cook', unique_name: 'mountcook', id: 355, travel_stats: { '355': '1' } },
        { name: 'North Island', unique_name: 'north-island', id: 370 },
        { name: 'South Island', unique_name: 'south-island', id: 371 },
        { name: 'Akaroa', unique_name: 'akaroa', id: 374, travel_stats: { '374': '2' } },
      ],
      name: 'New Zealand',
      iso_code: 'NZ',
      unique_name: 'new-zealand',
      id: 1,
    },
    {
      cities: [{ name: 'San Juan', unique_name: 'san-juan', id: 301 }, { name: 'Malay', unique_name: 'malay', id: 303 }],
      name: 'Philippines',
      iso_code: 'PH',
      unique_name: 'philippines',
      id: 177,
    },
    {
      cities: [
        { name: 'Cape Town', unique_name: 'cape-town', id: 157, travel_stats: { '168': '1' } },
        { name: 'Johannesburg', unique_name: 'johannesburg', id: 158, travel_stats: { '157': '1', '158': '2', '165': '1' } },
        { name: 'Port Elizabeth', unique_name: 'port-elizabeth', id: 161, travel_stats: { '157': '1' } },
        { name: 'Victoria Falls', unique_name: 'victoriafalls', id: 358 },
      ],
      name: 'South Africa',
      iso_code: 'ZA',
      unique_name: 'south-africa',
      id: 206,
    },
    {
      cities: [
        { name: 'Barcelona', unique_name: 'barcelona', id: 213 },
        { name: 'Valencia', unique_name: 'valencia', id: 337, travel_stats: { '337': '1' } },
        { name: 'San Sebastian', unique_name: 'san-sebastian', id: 338, travel_stats: { '338': '1' } },
        { name: 'Ibiza', unique_name: 'ibiza', id: 339, travel_stats: { '339': '1' } },
      ],
      name: 'Spain',
      iso_code: 'ES',
      unique_name: 'spain',
      id: 208,
    },
    {
      cities: [{ name: 'Negombo', unique_name: 'negombo', id: 304 }],
      name: 'Sri Lanka',
      iso_code: 'LK',
      unique_name: 'sri-lanka',
      id: 209,
    },
    {
      cities: [
        { name: 'Bangkok', unique_name: 'bangkok', id: 196 },
        { name: 'Chiang Mai', unique_name: 'chiang-mai', id: 197 },
        { name: 'Krabi', unique_name: 'krabi', id: 199 },
      ],
      name: 'Thailand',
      iso_code: 'TH',
      unique_name: 'thailand',
      id: 15,
    },
    {
      cities: [
        { name: 'Hue', unique_name: 'hue', id: 115 },
        { name: 'Hanoi', unique_name: 'hanoi', id: 219 },
        { name: 'Ho Chi Minh', unique_name: 'ho-chi-minh-1', id: 230 },
        { name: 'Hoi An', unique_name: 'hoi-an-1', id: 231 },
      ],
      name: 'Vietnam',
      iso_code: 'VN',
      unique_name: 'vietnam',
      id: 16,
    },
  ],
}
