export enum UiActionTypes {
  MOBILE_MENU_OPENED = "MOBILE_MENU_OPENED",
  MOBILE_MENU_CLOSED = "MOBILE_MENU_CLOSED",
  MOBILE_SEARCH_OPENED = "MOBILE_SEARCH_OPENED",
  MOBILE_SEARCH_CLOSED = "MOBILE_SEARCH_CLOSED",
  SEARCH_TYPE_CHANGED = "SEARCH_TYPE_CHANGED"
}